# -*- coding: utf-8 -*-
"""OLD_Fake_reviews+detection_using_XLM_RoBerta

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/sideys/old-fake-reviews-detection-using-xlm-roberta.70af108e-e5fa-4620-b05b-bde9e82ab502.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250619/auto/storage/goog4_request%26X-Goog-Date%3D20250619T124244Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D2929f39b55c5ff360611bc0643bd7b413f76e4ac9a68ca59951e2280f9cb4fa177183d5852fb62d9b35de4343470678bd6389455026b905663698bb2145af025cd5d7206c9958a47ff7c2d57324fc9340bb3c11649c509abc370954bcc93b6ae8c352549df8169c3c53b03a09dddf9dd5250c3f67421abbbe8c8b3777316512b9c23da8faa266bde363466f223484b2dc4a65c570911b5890f8d0089eb414ba30dc4710a179c4abf7052065b4c16da2e7987960e84c8cfd01677d5b91c80b11edd7161b41894ab7e93cedb0a4b7a66789a1a5761a8fa49b321b118218bf49c86b7850ead8a33d4b12e40ebdd834484f40231097e382d8992f60c509b3289702d
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

sideys_fake_reviewss_old_path = kagglehub.dataset_download('sideys/fake-reviewss-old')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

!pip install datasets evaluate
from datasets import DatasetDict, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import numpy as np
import evaluate
from datasets import load_dataset
from transformers import DataCollatorWithPadding

dataset_dict = load_dataset('csv', data_files='/kaggle/input/fake-reviewss-old/fake_review_old.csv')

tokenizer_name = "FacebookAI/xlm-roberta-base"
model_name = "FacebookAI/xlm-roberta-base"
id2label = {0: "FAKE", 1: "REAL"}
label2id = {"FAKE": 0, "REAL": 1}

tokenizer = AutoTokenizer.from_pretrained(tokenizer_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2, id2label=id2label, label2id=label2id)

dataset_dict = dataset_dict["train"].train_test_split(test_size=0.2, seed=42)
train_dataset = dataset_dict["train"]
test_dataset = dataset_dict["test"]

train_dataset = train_dataset.filter(lambda x: x['text'] is not None)
test_dataset =  test_dataset.filter(lambda x: x['text'] is not None)

def tokenize_function(examples):
    return tokenizer(examples['text'], padding="max_length", truncation=True)

encoded_train_dataset = train_dataset.map(tokenize_function, batched=True)
encoded_test_dataset = test_dataset.map(tokenize_function, batched=True)

encoded_train_dataset = encoded_train_dataset.rename_column("label", "labels")
encoded_train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

encoded_test_dataset = encoded_test_dataset.rename_column("label", "labels")
encoded_test_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

# Data collator for dynamic padding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

!pip install torch
import torch

import os
os.environ["WANDB_MODE"] = "disabled"
import wandb
wandb.init(mode="disabled")

# prompt: generate compute metrics for the collab model using classification report

import numpy as np
from sklearn.metrics import classification_report

# Define the metric
metric = evaluate.load("accuracy")

# Define a function to compute metrics
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=False,
)

# Create Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_train_dataset,
    eval_dataset=encoded_test_dataset,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# Train the model
trainer.train()

# Make predictions on the test set
predictions = trainer.predict(encoded_test_dataset)

# Get predicted labels
predicted_labels = np.argmax(predictions.predictions, axis=1)

# Get true labels
true_labels = predictions.label_ids

# Generate classification report
print(classification_report(true_labels, predicted_labels, target_names=['FAKE', 'REAL']))

# prompt: generate confusion matrix

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Generate confusion matrix
cm = confusion_matrix(true_labels, predicted_labels)

# Plot confusion matrix
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=['FAKE', 'REAL'], yticklabels=['FAKE', 'REAL'])
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.show()

# import wandb
# wandb.login(key="b7459d2d1cad50b1b2f3388aa0792a3495511f1d")